spring:
  application:
    name: theatre-manager
    pagination:
      max-size: 50

  r2dbc:
    url: r2dbc:postgresql://localhost:5401/thetre_db
    username: postgres
    password: postgres

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 0

logging:
  level:
    org.springframework: INFO
